# Generated by Django 2.2.2 on 2019-07-06 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('albumName', models.CharField(max_length=255)),
                ('alterTime', models.DateTimeField(default=datetime.datetime(2019, 7, 6, 11, 52, 6, 128691))),
                ('tag_1', models.CharField(max_length=100)),
                ('custom_Tag_1', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email_CheckCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_addr', models.EmailField(max_length=254)),
                ('check_code', models.CharField(max_length=6, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 7, 6, 11, 52, 6, 130687))),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('pictureID', models.IntegerField(primary_key=True, serialize=False)),
                ('pictureName', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('alterTime', models.DateTimeField(default=datetime.datetime(2019, 7, 6, 11, 52, 6, 126699))),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('username', models.CharField(max_length=16)),
                ('account', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
                ('administration', models.BooleanField(max_length=1)),
                ('e_mail_address', models.CharField(max_length=40)),
                ('VIP', models.BooleanField()),
                ('registerTime', models.DateField(default=datetime.date(2019, 7, 6))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAlbum.UserList')),
                ('pictureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAlbum.Storage')),
            ],
        ),
        migrations.CreateModel(
            name='PitTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_1', models.CharField(max_length=100)),
                ('tag_2', models.CharField(max_length=100)),
                ('tag_3', models.CharField(max_length=100)),
                ('custom_Tag_1', models.CharField(max_length=20, null=True)),
                ('pictureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAlbum.Storage')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAlbum.Album')),
                ('pictureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAlbum.Storage')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAlbum.UserList'),
        ),
        migrations.AddField(
            model_name='album',
            name='pictureID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAlbum.Storage'),
        ),
    ]
