# Generated by Django 2.2.2 on 2019-06-26 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('albumName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('pictureID', models.IntegerField(primary_key=True, serialize=False)),
                ('pictureName', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('username', models.CharField(max_length=16)),
                ('account', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIP', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAlbum.UserList')),
                ('pictureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAlbum.Storage')),
            ],
        ),
        migrations.CreateModel(
            name='PitTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_1', models.CharField(max_length=30)),
                ('tag_2', models.CharField(max_length=30)),
                ('tag_3', models.CharField(max_length=30)),
                ('custom_Tag_1', models.CharField(max_length=30)),
                ('custom_Tag_2', models.CharField(max_length=30)),
                ('custom_Tag_3', models.CharField(max_length=30)),
                ('pictureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAlbum.Storage')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_1', models.CharField(max_length=30)),
                ('tag_2', models.CharField(max_length=30)),
                ('tag_3', models.CharField(max_length=30)),
                ('custom_Tag_1', models.CharField(max_length=30)),
                ('custom_Tag_2', models.CharField(max_length=30)),
                ('custom_Tag_3', models.CharField(max_length=30)),
                ('albumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAlbum.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAlbum.UserList'),
        ),
    ]
