# Generated by Django 2.2.2 on 2019-07-09 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAlbum', '0002_auto_20190706_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='pictureID',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userlist',
            name='settings',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='alterTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 9, 21, 1, 366173)),
        ),
        migrations.AlterField(
            model_name='email_checkcode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 9, 21, 1, 368167)),
        ),
        migrations.AlterField(
            model_name='storage',
            name='alterTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 9, 21, 1, 364178)),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='registerTime',
            field=models.DateField(default=datetime.date(2019, 7, 9)),
        ),
    ]
