# Generated by Django 2.2.2 on 2019-07-09 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAlbum', '0003_auto_20190709_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='alterTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 18, 33, 58, 150343)),
        ),
        migrations.AlterField(
            model_name='email_checkcode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 18, 33, 58, 153335)),
        ),
        migrations.AlterField(
            model_name='storage',
            name='alterTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 18, 33, 58, 149346)),
        ),
        migrations.AlterField(
            model_name='storage',
            name='pictureID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
