# Generated by Django 2.2.2 on 2019-07-10 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAlbum', '0004_auto_20190709_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='alterTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 15, 39, 52, 65113)),
        ),
        migrations.AlterField(
            model_name='email_checkcode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 15, 39, 52, 67108)),
        ),
        migrations.AlterField(
            model_name='storage',
            name='alterTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 15, 39, 52, 63123)),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='registerTime',
            field=models.DateField(default=datetime.date(2019, 7, 10)),
        ),
    ]
