# Generated by Django 2.2.2 on 2019-07-10 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAlbum', '0006_auto_20190710_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='info',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='alterTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 16, 58, 44, 571582)),
        ),
        migrations.AlterField(
            model_name='email_checkcode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 16, 58, 44, 573548)),
        ),
        migrations.AlterField(
            model_name='storage',
            name='alterTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 16, 58, 44, 569588)),
        ),
    ]
