# Generated by Django 2.2.2 on 2019-07-10 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAlbum', '0009_auto_20190710_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='alterTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 25, 14, 60275)),
        ),
        migrations.AlterField(
            model_name='email_checkcode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 25, 14, 62270)),
        ),
        migrations.AlterField(
            model_name='storage',
            name='alterTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 25, 14, 59277)),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='settings',
            field=models.CharField(default="['#23262E', '#393D49']", max_length=150),
        ),
    ]
