# Generated by Django 2.2.2 on 2019-07-11 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAlbum', '0010_auto_20190710_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleteTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='alterTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 15, 33, 46, 638739)),
        ),
        migrations.AlterField(
            model_name='email_checkcode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 15, 33, 46, 640736)),
        ),
        migrations.AlterField(
            model_name='storage',
            name='alterTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 15, 33, 46, 636745)),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='registerTime',
            field=models.DateField(default=datetime.date(2019, 7, 11)),
        ),
    ]
